spring.docker.compose.enabled=false
spring.datasource.url=jdbc:h2:file:${genshin.desktop.home:${user.home}/.genshinapp/desktop}/database/genshinapp;MODE=MySQL;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.datasource.hikari.maximum-pool-size=4

server.address=127.0.0.1
server.port=47831
server.shutdown=graceful

genshin.runtime.desktop=true
genshin.runtime.open-browser=false
genshin.runtime.tray-enabled=true
genshin.runtime.show-window=true
genshin.content.cache-directory=${genshin.desktop.home:${user.home}/.genshinapp/desktop}/cache
